"""add token publico to resumo salvo

Revision ID: 2023b09ef884
Revises: 23594d3ded9b
Create Date: 2026-04-29 16:33:01.498972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2023b09ef884'
down_revision = '23594d3ded9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumos_salvos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_publico', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(
            'uq_resumos_salvos_token_publico',
            ['token_publico']
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumos_salvos', schema=None) as batch_op:
        batch_op.drop_constraint('uq_resumos_salvos_token_publico', type_='unique')
        batch_op.drop_column('token_publico')

    # ### end Alembic commands ###
