"""add pessoa to resumo salvo

Revision ID: 23594d3ded9b
Revises: 59725c433a26
Create Date: 2026-04-29 14:10:30.326757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23594d3ded9b'
down_revision = '59725c433a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumos_salvos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pessoa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_resumos_salvos_pessoa_id_pessoas',
            'pessoas',
            ['pessoa_id'],
            ['id']
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumos_salvos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_resumos_salvos_pessoa_id_pessoas', type_='foreignkey')
        batch_op.drop_column('pessoa_id')

    # ### end Alembic commands ###
