"""empty message

Revision ID: 379443a35ab6
Revises: 
Create Date: 2025-05-07 14:03:47.093168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379443a35ab6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planejamento_itens', schema=None) as batch_op:
        batch_op.alter_column('suplemento_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'suplementos', ['suplemento_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planejamento_itens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'suplementos', ['suplemento_id'], ['id'])
        batch_op.alter_column('suplemento_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
