"""Adiciona nome e sobrenome ao usuário

Revision ID: 3c651b778be6
Revises: 
Create Date: 2025-04-30 11:51:29.607440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c651b778be6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=150), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('sobrenome', sa.String(length=150), nullable=False, server_default=''))
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sobrenome')
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
