"""add planejamento item

Revision ID: 3cdecfc28f71
Revises: 
Create Date: 2025-04-25 15:40:04.244232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cdecfc28f71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planejamento_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suplemento_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['suplemento_id'], ['suplementos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planejamento_itens')
    # ### end Alembic commands ###
