"""add varios campos

Revision ID: 66df817bb04f
Revises: e9f1f4527332
Create Date: 2026-03-23 14:24:30.541187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66df817bb04f'
down_revision = 'e9f1f4527332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gordura_saturada', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fibras_alimentares', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vit_d', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('acido_pantotenico', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('acido_folico', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tirosina', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('colina', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vitamina_d', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.drop_column('vitamina_d')
        batch_op.drop_column('colina')
        batch_op.drop_column('tirosina')
        batch_op.drop_column('acido_folico')
        batch_op.drop_column('acido_pantotenico')
        batch_op.drop_column('vit_d')
        batch_op.drop_column('fibras_alimentares')
        batch_op.drop_column('gordura_saturada')

    # ### end Alembic commands ###
