"""Add comentario and ingredientes to Suplemento

Revision ID: 75ec620d625a
Revises: d13d1d8b4eff
Create Date: 2025-05-20 14:34:56.075647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ec620d625a'
down_revision = 'd13d1d8b4eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ingredientes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.drop_column('ingredientes')
        batch_op.drop_column('comentario')

    # ### end Alembic commands ###
