"""Add comentario and ingredientes corretamente

Revision ID: 85d55439c18c
Revises: a223cd5683f3
Create Date: 2025-07-21 09:44:02.265653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d55439c18c'
down_revision = 'a223cd5683f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloro', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fosforo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('zinco', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.drop_column('zinco')
        batch_op.drop_column('fosforo')
        batch_op.drop_column('cloro')

    # ### end Alembic commands ###
