"""add suplementos_utilizados to resumos_salvos

Revision ID: 8b2e20a92b53
Revises: 
Create Date: 2025-05-13 11:01:17.352381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2e20a92b53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumos_salvos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suplementos_utilizados', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumos_salvos', schema=None) as batch_op:
        batch_op.drop_column('suplementos_utilizados')

    # ### end Alembic commands ###
