"""add niacina e vit e to suplemento

Revision ID: 9ff4c856af21
Revises: 85d55439c18c
Create Date: 2025-07-21 11:32:48.316099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff4c856af21'
down_revision = '85d55439c18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('niacina', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vit_e', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.drop_column('vit_e')
        batch_op.drop_column('niacina')

    # ### end Alembic commands ###
