"""add gramas_por_porcao e descricao_porcao ao suplemento

Revision ID: a223cd5683f3
Revises: 75ec620d625a
Create Date: 2025-05-21 14:51:26.248156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a223cd5683f3'
down_revision = '75ec620d625a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planejamento_itens', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gramas_por_porcao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('descricao_porcao', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.drop_column('descricao_porcao')
        batch_op.drop_column('gramas_por_porcao')

    with op.batch_alter_table('planejamento_itens', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
