"""add vit_ferro to suplementos

Revision ID: a36ff6087ba0
Revises: 9ff4c856af21
Create Date: 2026-03-23 11:30:27.189218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36ff6087ba0'
down_revision = '9ff4c856af21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vit_ferro', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.drop_column('vit_ferro')

    # ### end Alembic commands ###
