"""add suplementos_utilizados to resumos_salvos

Revision ID: b32ae4d5189c
Revises: 
Create Date: 2025-05-10 18:27:13.808014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32ae4d5189c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planejamento_itens', schema=None) as batch_op:
        batch_op.alter_column('suplemento_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('planejamento_itens_suplemento_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'suplementos', ['suplemento_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('resumos_salvos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suplementos_utilizados', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumos_salvos', schema=None) as batch_op:
        batch_op.drop_column('suplementos_utilizados')

    with op.batch_alter_table('planejamento_itens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('planejamento_itens_suplemento_id_fkey', 'suplementos', ['suplemento_id'], ['id'])
        batch_op.alter_column('suplemento_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
