"""add varios campos suplementos

Revision ID: cf45f2d3b414
Revises: 66df817bb04f
Create Date: 2026-03-26 11:04:05.325829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf45f2d3b414'
down_revision = '66df817bb04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proteina', sa.Float(), nullable=True))
        batch_op.drop_column('vitamina_d')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vitamina_d', sa.FLOAT(), nullable=True))
        batch_op.drop_column('proteina')

    # ### end Alembic commands ###
