"""Add ordem to ResumoSalvo

Revision ID: d13d1d8b4eff
Revises: ec27057be59a
Create Date: 2025-05-19 14:47:35.666863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13d1d8b4eff'
down_revision = None  # era 'ec27057be59a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumos_salvos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordem', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumos_salvos', schema=None) as batch_op:
        batch_op.drop_column('ordem')

    # ### end Alembic commands ###
