"""add vit_b5 to suplementos

Revision ID: e9f1f4527332
Revises: a36ff6087ba0
Create Date: 2026-03-23 13:15:18.346128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f1f4527332'
down_revision = 'a36ff6087ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vit_b5', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suplementos', schema=None) as batch_op:
        batch_op.drop_column('vit_b5')

    # ### end Alembic commands ###
