"""Fake remove ordem

Revision ID: ec27057be59a
Revises: 
Create Date: 2025-05-19 14:45:52.954891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec27057be59a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumos_salvos', schema=None) as batch_op:
        batch_op.drop_column('ordem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumos_salvos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordem', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
